"""Minimal HASLAB compiler components for the M6 vertical slice."""

# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Zubin Bhuyan

from .hxb import Section, SectionType, build_hxb
from .c2f import (
    C2fBlockSpec,
    C2fConvSpec,
    RawConvSpec,
    compile_first_c2f,
    compile_pinned_first_c2f,
    load_pinned_first_c2f,
    load_pinned_through_backbone,
    load_pinned_through_first_neck,
    load_pinned_through_first_bottom_up_neck,
    load_pinned_through_second_bottom_up_neck,
    load_pinned_through_detection_head,
    load_pinned_through_second_neck,
)
from .first_layer import compile_conv_silu_first_layer, compile_pinned_first_layer
from .graph import (
    AddOp,
    BottomUpNeckStageSpec,
    C2fExtension,
    C2fStageSpec,
    ConcatOp,
    ConcatI32Op,
    ConvRawOp,
    ConvSiluOp,
    GraphIR,
    GraphTensor,
    DetectionHeadBranchSpec,
    DetectionHeadSpec,
    FirstNeckStageSpec,
    MaxPoolOp,
    SPPFSpec,
    TopDownNeckStageSpec,
    Upsample2Op,
    build_backbone_graph,
    build_two_c2f_graph,
    build_c2f_graph,
    compile_graph,
    compile_pinned_through_second_c2f,
    compile_pinned_through_third_c2f,
    compile_pinned_through_backbone,
    compile_pinned_through_first_neck,
    compile_pinned_through_first_bottom_up_neck,
    compile_pinned_through_second_bottom_up_neck,
    compile_pinned_through_detection_head,
    compile_pinned_through_second_neck,
    extend_with_first_neck_stage,
    extend_with_bottom_up_neck_stage,
    extend_with_detection_head,
    extend_with_top_down_neck_stage,
    extend_with_sppf,
    first_stage,
)
from .pipeline import (
    ConvSiluLayerSpec,
    compile_conv_silu_pipeline,
    compile_pinned_first_two_layers,
    load_pinned_first_two_layers,
)
from .vertical_slice import (
    CompileError,
    compile_conv_silu_slice,
    compile_pinned_first_block,
    extract_input_patch,
)

__all__ = [
    "CompileError",
    "C2fBlockSpec",
    "BottomUpNeckStageSpec",
    "C2fConvSpec",
    "RawConvSpec",
    "C2fExtension",
    "C2fStageSpec",
    "AddOp",
    "ConcatOp",
    "ConcatI32Op",
    "ConvRawOp",
    "ConvSiluOp",
    "ConvSiluLayerSpec",
    "GraphIR",
    "GraphTensor",
    "DetectionHeadBranchSpec",
    "DetectionHeadSpec",
    "FirstNeckStageSpec",
    "MaxPoolOp",
    "SPPFSpec",
    "TopDownNeckStageSpec",
    "Upsample2Op",
    "Section",
    "SectionType",
    "build_hxb",
    "build_backbone_graph",
    "build_c2f_graph",
    "build_two_c2f_graph",
    "compile_conv_silu_first_layer",
    "compile_conv_silu_pipeline",
    "compile_conv_silu_slice",
    "compile_first_c2f",
    "compile_graph",
    "compile_pinned_first_block",
    "compile_pinned_first_c2f",
    "compile_pinned_first_layer",
    "compile_pinned_first_two_layers",
    "compile_pinned_through_second_c2f",
    "compile_pinned_through_third_c2f",
    "compile_pinned_through_backbone",
    "compile_pinned_through_first_neck",
    "compile_pinned_through_first_bottom_up_neck",
    "compile_pinned_through_second_bottom_up_neck",
    "compile_pinned_through_detection_head",
    "compile_pinned_through_second_neck",
    "extend_with_first_neck_stage",
    "extend_with_bottom_up_neck_stage",
    "extend_with_detection_head",
    "extend_with_top_down_neck_stage",
    "extend_with_sppf",
    "extract_input_patch",
    "first_stage",
    "load_pinned_first_two_layers",
    "load_pinned_first_c2f",
    "load_pinned_through_backbone",
    "load_pinned_through_first_neck",
    "load_pinned_through_first_bottom_up_neck",
    "load_pinned_through_second_bottom_up_neck",
    "load_pinned_through_detection_head",
    "load_pinned_through_second_neck",
]
